// Generated by WebFx

module webfx.website.application {

    // Direct dependencies modules
    requires javafx.graphics;
    requires webfx.platform.client.windowlocation;

    // Exported packages
    exports dev.webfx.website.application;

    // Provided services
    provides javafx.application.Application with dev.webfx.website.application.WebsiteApplication;

}