// Generated by WebFx

module webfx.website.application.javafx {

    // Direct dependencies modules
    requires webfx.kit.javafx;
    requires webfx.platform.client.websocketbus;
    requires webfx.platform.java.appcontainer.impl;
    requires webfx.platform.java.resource.impl;
    requires webfx.platform.java.scheduler.impl;
    requires webfx.platform.java.shutdown.impl;
    requires webfx.platform.java.websocket.impl;
    requires webfx.platform.java.windowhistory.impl;
    requires webfx.platform.java.windowlocation.impl;
    requires webfx.platform.shared.json.impl;
    requires webfx.platform.shared.log.impl.simple;
    requires webfx.website.application;

}